sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: CPB5iEs/3t4t091D0O/hXPIqtz4pTIhsGpCen0rRdZh7h1fWQoDqTKN23Qw2XUOW4aNiGRfMlOlTEZ+vbXOoFak1Ur7subKPy2iB5d0xwQVgeC4rMm4kn8RIsVOqH3Xu3+xOWpR8gF8gIbpBhn7sg+X4GcCerfRZxvRS5i+lQiF7wdnJp6Ya58N49N+a/VrI7CELSnzdpWP78bdim7uDDa1/3yt7AxjnYFA8HL7W1OW8FqTfxrwP0XjsRsmYeb7htX0N6KV2M56eqhzUGLzEmF9NIunXKd6c1gbLGzLoyc15WJXgZcsGTzXu16mGEeuDEBWuYZH7cNFuo7H7gpzJywhn3R5+Rxzp9J/AU57gknhXuNfIHkAHWkZno07hXXoIlKrrRRAtaT+sk47hKoOzkIDJ8CJnoi7wshGCUVa5Qsmi9L0ApePdQA4dtqw9Kt6YvZq28zDVeWUgktJIrwWV94TWKvWeik+hWX+5gsKl94x55uP3Z58DE9Pz0bwQ/2hWORfaPn0kluD8nOXxTqG6BagXX5KLoQ6b1vMsMcu5q4ykbIY83uvhVZ3DU5ZlNyW3qooGbOvUvgv6niyblveolZb+qu2/pl8Hwq2IR1Vb3rhraAyMBRhPVhqCcEnoYcTM0uDGOIekmfhjFcrqLGA9DgxnAlZLBTBrOtvnHGjmlh0=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: qgwQpIHjqLHziA0WX/N035Kq0I0DpeT7Ir/NzLLUjJI3Bw+vvl5SPJ7kI4Pahp51MKLGmbbJmrtkVH6Dx6UTH6DUtkfRoxmkWqNs9Zo8ga0r5WD7nakxL07s1D9gS1kry8FrRFNFx3H1kSgI4uFtbiAGxILG9/nP7iRXC9BiS+VTnoxSuubtJzAUIsMQSS7SLr+j958ztgJ7rv+KT25WKulWmW2Eqd05/L18Igyjkmex6pnkBHDY2Ss0ASIg5h/totFI6iLHnc1Pu9woIvF2Rm33pjNGHdRnN3qqrd7QXL2f0MUkZreV2++4PlBY/nLcFKDgsn2f6UgRi9HazX+8lRdAHCyKGFCPLaC/CLAJxDcHejuRMIlID35SS02JM4sYqodbBQuYzRhfH9oW9XY0Yewmp5Z2sxirntLZc4T6cvl2tRD96KtCVxdntMvk8N4Akn7a+HoQ9Efd0vInJi/rGen7NbJbBvp+h8A1XIJQv2G04S5h4G2dFdEmASMXg0c+UJ23TSOnw4WktGxFpjCTKcHDoE5MPEH9ndBdlH9YBIRiGkZvSlbtsDKP8qzb5qNdZK5GO+CX5/BX//Hl783B07NUqTGHzIyhZF+0xzY8lTHn1GN2+pzSp2aWmdq2Wk2tLZS4+B/jw+CN7e/ajT+g8FrOK/HpKO2DAv0MBQZSJR0=
